// <auto-generated />
using System;
using System.Text.Json;
using AWE.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AWE.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401045508_AddfieldIsTestForInstance")]
    partial class AddfieldIsTestForInstance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AWE.Domain.Entities.ApprovalToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<Guid>("PointerId")
                        .HasColumnType("uuid")
                        .HasColumnName("pointer_id");

                    b.Property<string>("TokenString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_string");

                    b.HasKey("Id")
                        .HasName("pk_approval_token");

                    b.ToTable("ApprovalToken", (string)null);
                });

            modelBuilder.Entity("AWE.Domain.Entities.ExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event");

                    b.Property<Guid?>("ExecutionPointerId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_pointer_id");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("node_id");

                    b.Property<string>("WorkerId")
                        .HasColumnType("text")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_execution_log");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_execution_logs_created_at");

                    b.HasIndex("ExecutionPointerId")
                        .HasDatabaseName("ix_execution_log_execution_pointer_id");

                    b.HasIndex("InstanceId")
                        .HasDatabaseName("ix_execution_logs_instance_id");

                    b.HasIndex("InstanceId", "CreatedAt")
                        .HasDatabaseName("ix_execution_logs_instance_created");

                    b.ToTable("ExecutionLog", (string)null);
                });

            modelBuilder.Entity("AWE.Domain.Entities.ExecutionPointer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("ROOT")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("LeasedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("leased_by");

                    b.Property<DateTime?>("LeasedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leased_until");

                    b.Property<JsonDocument>("Output")
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_token_id");

                    b.Property<Guid?>("PredecessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("predecessor_id");

                    b.Property<DateTime?>("ResumeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resume_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<bool>("Routed")
                        .HasColumnType("boolean")
                        .HasColumnName("routed");

                    b.Property<JsonDocument>("Scope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("step_id");

                    b.HasKey("Id")
                        .HasName("pk_execution_pointers");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_execution_pointers_created_at");

                    b.HasIndex("InstanceId", "Active")
                        .HasDatabaseName("ix_execution_pointers_instance_active");

                    b.HasIndex("Status", "LeasedUntil")
                        .HasDatabaseName("ix_execution_pointers_zombie")
                        .HasFilter("\"status\" = 'Running'");

                    b.HasIndex("InstanceId", "ParentTokenId", "StepId")
                        .HasDatabaseName("ix_execution_pointers_join_barrier");

                    b.ToTable("ExecutionPointers", (string)null);
                });

            modelBuilder.Entity("AWE.Domain.Entities.JoinBarrier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("ArrivedTokens")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("arrived_tokens");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean")
                        .HasColumnName("is_released");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("integer")
                        .HasColumnName("required_count");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("step_id");

                    b.HasKey("Id")
                        .HasName("pk_join_barrier");

                    b.HasIndex("IsReleased")
                        .HasDatabaseName("ix_join_barriers_is_released");

                    b.HasIndex("InstanceId", "StepId")
                        .IsUnique()
                        .HasDatabaseName("ix_join_barriers_instance_step");

                    b.ToTable("JoinBarrier", (string)null);
                });

            modelBuilder.Entity("AWE.Domain.Entities.PluginPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("execution_mode");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unique_name");

                    b.HasKey("Id")
                        .HasName("pk_plugin_package");

                    b.HasIndex("UniqueName")
                        .IsUnique()
                        .HasDatabaseName("ix_plugin_packages_unique_name");

                    b.ToTable("PluginPackage", (string)null);
                });

            modelBuilder.Entity("AWE.Domain.Entities.PluginVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("ConfigSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_schema");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("ExecutionMetadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("execution_metadata");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("ReleaseNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("release_notes");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_plugin_version");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_plugin_versions_is_active");

                    b.HasIndex("PackageId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_plugin_versions_package_version");

                    b.ToTable("PluginVersion", (string)null);
                });

            modelBuilder.Entity("AWE.Domain.Entities.SystemAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("table_name");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_system_audit_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_system_audit_logs_created_at");

                    b.HasIndex("TableName", "RecordId")
                        .HasDatabaseName("ix_system_audit_logs_table_record");

                    b.ToTable("SystemAuditLogs", (string)null);
                });

            modelBuilder.Entity("AWE.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_json");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("UiJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ui_json");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workflow_definition");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_workflow_definitions_created_at");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_workflow_definitions_is_published");

                    b.HasIndex("Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_definitions_name_version");

                    b.ToTable("WorkflowDefinition", (string)null);
                });

            modelBuilder.Entity("AWE.Domain.Entities.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("ContextData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("context_data");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("definition_version");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsTest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_test");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<Guid?>("ParentInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_instance_id");

                    b.Property<Guid?>("ParentPointerId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_pointer_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_workflow_instance");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_workflow_instances_created_at");

                    b.HasIndex("DefinitionId")
                        .HasDatabaseName("ix_workflow_instances_definition_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_workflow_instances_status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_workflow_instances_status_created_at");

                    b.ToTable("WorkflowInstance", (string)null);
                });

            modelBuilder.Entity("AWE.Domain.Entities.WorkflowSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cron_expression");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workflow_schedule");

                    b.HasIndex("DefinitionId")
                        .HasDatabaseName("ix_workflow_schedule_definition_id");

                    b.HasIndex("IsActive", "NextRunAt")
                        .HasDatabaseName("ix_workflow_schedule_active_next_run");

                    b.ToTable("WorkflowSchedule", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("receive_count");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_inbox_state");

                    b.HasAlternateKey("MessageId", "ConsumerId")
                        .HasName("ak_inbox_state_message_id_consumer_id");

                    b.HasIndex("Delivered")
                        .HasDatabaseName("ix_inbox_state_delivered");

                    b.ToTable("InboxState", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueue_time");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fault_address");

                    b.Property<string>("Headers")
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_consumer_id");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("response_address");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_time");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_address");

                    b.HasKey("SequenceNumber")
                        .HasName("pk_outbox_message");

                    b.HasIndex("EnqueueTime")
                        .HasDatabaseName("ix_outbox_message_enqueue_time");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("ix_outbox_message_expiration_time");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_outbox_id_sequence_number");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_n");

                    b.ToTable("OutboxMessage", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("OutboxId")
                        .HasName("pk_outbox_state");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_outbox_state_created");

                    b.ToTable("OutboxState", (string)null);
                });

            modelBuilder.Entity("AWE.Domain.Entities.ExecutionLog", b =>
                {
                    b.HasOne("AWE.Domain.Entities.ExecutionPointer", "ExecutionPointer")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("ExecutionPointerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_execution_log_execution_pointers_execution_pointer_id");

                    b.HasOne("AWE.Domain.Entities.WorkflowInstance", "Instance")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_execution_log_workflow_instances_instance_id");

                    b.Navigation("ExecutionPointer");

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("AWE.Domain.Entities.ExecutionPointer", b =>
                {
                    b.HasOne("AWE.Domain.Entities.WorkflowInstance", "Instance")
                        .WithMany("ExecutionPointers")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_execution_pointers_workflow_instances_instance_id");

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("AWE.Domain.Entities.JoinBarrier", b =>
                {
                    b.HasOne("AWE.Domain.Entities.WorkflowInstance", "Instance")
                        .WithMany("JoinBarriers")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_join_barrier_workflow_instances_instance_id");

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("AWE.Domain.Entities.PluginVersion", b =>
                {
                    b.HasOne("AWE.Domain.Entities.PluginPackage", "Package")
                        .WithMany("Versions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plugin_version_plugin_package_package_id");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("AWE.Domain.Entities.WorkflowInstance", b =>
                {
                    b.HasOne("AWE.Domain.Entities.WorkflowDefinition", "Definition")
                        .WithMany("Instances")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_instance_workflow_definition_definition_id");

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("AWE.Domain.Entities.WorkflowSchedule", b =>
                {
                    b.HasOne("AWE.Domain.Entities.WorkflowDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_schedule_workflow_definition_definition_id");

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .HasConstraintName("fk_outbox_message_outbox_state_outbox_id");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId")
                        .HasConstraintName("fk_outbox_message_inbox_state_inbox_message_id_inbox_consumer_id");
                });

            modelBuilder.Entity("AWE.Domain.Entities.ExecutionPointer", b =>
                {
                    b.Navigation("ExecutionLogs");
                });

            modelBuilder.Entity("AWE.Domain.Entities.PluginPackage", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("AWE.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("AWE.Domain.Entities.WorkflowInstance", b =>
                {
                    b.Navigation("ExecutionLogs");

                    b.Navigation("ExecutionPointers");

                    b.Navigation("JoinBarriers");
                });
#pragma warning restore 612, 618
        }
    }
}
