# ----------------------------------------------------------------------------
# RABBITMQ CONFIGURATION FILE
# Project: AWE Platform
# ----------------------------------------------------------------------------

# 1. RESOURCE LIMITS
vm_memory_high_watermark.relative = 0.7

disk_free_limit.absolute = 2GB


# 2. AUTOMATION & MANAGEMENT (Tự động hóa)
# Tự động nạp file definitions (VHost, User, Permissions) khi khởi động.
# Đây là dòng thay thế cho biến môi trường "RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS" cũ.
#management.load_definitions = /etc/rabbitmq/rabbitmq_definitions.json


# 3. NETWORKING & LOGGING (Mạng & Ghi log)
# Cổng mặc định (Standard AMQP port)
listeners.tcp.default = 5672

# Xuất log ra Console (stdout) để Docker/Aspire Dashboard hiển thị được.
log.console = true
log.console.level = info

# Heartbeat timeout: Giúp phát hiện kết nối chết nhanh hơn (mặc định 60s)
heartbeat = 60
